repos:
  - repo: local
    hooks:
      - id: rubocop
        name: RuboCop
        entry: bundle exec rubocop
        language: ruby
        types: [ruby]
      - id: rspec
        name: RSpec
        entry: bundle exec rspec
        language: ruby
        types: [ruby]
