require:
  - rubocop-graphql
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  NewCops: enable
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
GraphQL/ObjectDescription:
  Enabled: false
GraphQL/FieldDescription:
  Enabled: false
GraphQL/ArgumentDescription:
  Enabled: false
Rails/WhereExists:
  Enabled: false
GraphQL/ExtractType:
  Enabled: false
GraphQL/ExtractInputType:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
