services:
  mongo:
    image: mongo:6.0
    networks:
      - app
    volumes:
      - db:/data/db
    ports:
      - "27017:27017"

  web:
    build: .
    networks:
      - app
    volumes:
      - ./:/app
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    env_file:
      - .env.docker
    command: bundle exec rails server -b 0.0.0.0 -p 5000

networks:
  app:

volumes:
  db:
