production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        database: writeonapi

development:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        database: writeonapi
        direct_connection: true

test:
  clients:
    default:
      uri: <%= ENV.fetch('MONGODB_URI', 'mongodb://localhost:27017/writeon_test') %>
      options:
        server_selection_timeout: 5
