production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        database: writeonapi

development:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        database: writeonapi
        direct_connection: true

test:
  clients:
    default:
      uri: <%= ENV.fetch('MONGODB_URI', 'mongodb://127.0.0.1:27017/writeon_test') %>
      options:
        read:
          mode: :primary
        max_pool_size: 1
        direct_connection: true
